# -*- coding: utf-8 -*-
"""MFDS.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W18tF1Y4fefITzzlQIAGpDT8xuFJ3Gqa
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.feature_extraction.text import CountVectorizer

data=pd.read_csv('/content/CVD_cleaned.csv')
print(data.head())

data=pd.get_dummies(data,columns=['General_Health','Checkup','Exercise','Skin_Cancer','Other_Cancer','Depression','Diabetes','Arthritis','Sex','Age_Category','Smoking_History','Alcohol_Consumption'],drop_first=True)

x=data.drop('Heart_Disease',axis=1)
y=data['Heart_Disease']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=GaussianNB()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy}')

report=classification_report(y_test,y_pred)
print(f'Classification Report:\n{report}')
print(report)