# -*- coding: utf-8 -*-
"""Python1 basic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kdQvQnhkL5qr-po1Sc5b0C19Bt9IzFc
"""

a=10
print(a)
b=17.75
print(b)
c="Hello"
print(c)
d=True
print(d)

"""Swappimg Number without using third variable"""

a=10
b=25
print("Before swpping :")
print("a=",a,"b=",b)
a,b=b,a
print("after swapping:")
print("a=",a,"b=",b)

"""Swapping number using third variable"""

a,b=10,25
print("Before swpping :")
print("a=",a,"b=",b)
temp=a
a=b
b=temp
print("after swapping:")
print("a=",a,"b=",b)

"""Operator"""

# Commentnt line
# Arithmatic Operator + - * / // **
a=10
b=2
c=a+b
print("c=",c)
c=a-b
print("c=",c)
c=a*b
print("c=",c)
c=a/b
print("c=",c)
c=a//b
print("c=",c)
c=a**b
print("c=",c)

"""Relational Operator"""

# Relational Operator
 # <     <=       >        >=        ==       !=
 a=10
 b=20
 print(a<=b)
 print(a<b)
 print(a>b)
 print(a>=b)
 print(a==b)
 print(a!=b)

"""Logical OPerator"""

# Logical Operator
# Logical AND
#  and
# T and T = T
a=10
b=20
c=30
print(a<b and a<c)
print(a<b and c<a)
# Logical OR
# or F or F = F
print(a<b or c<a)
# Logical NOT
# not
# not(T) = F
# NOT(F) = T
print(not(a<b))

"""Shortcut Operator"""

# a=10 asignment operator
# += shortcut operator
# a+=5
a=10
b=20
a+=b
print(a)
a-=b
print(a)
a*=b
print(a)
a/=b
print(a)
a//=b
print(a)
a**=b
print(a)

"""Bitwise Operator"""

# 0&0=0   1&0 =0  0&1 =0    1&1=1
# bitwise and
#             8    4     2   1
#  a           1    0     1   0
#  b          0    1     0   0
# output     0    0     0   0
a=10
b=4
print(a&b)
# 0/0=0  0/1=1   1/0=1    1/1=1
# bitwise or
#            8     4   2    1
# a          1     0    1    0
# b          0     1     0   0
# output     1     1     1    0
print(a/b)
#Bitwise XOR
# 0^0=0    0^1=1   1^0=1    1^1=1
#         8       4       2      1
#a        1       0        1     0
#b        0       1        0      0
print(a^b)
#Leftshift OPerator
# b*2
# 4*4
# 16
print(b<<2)
# rightshift opertor
# 4/2*2
# 1
print(b>>2)

"""# **Type conversion **
Object can be explicity from one type to another as long as the the conversion make sense.This is called typecasting.
-> Ints can be cast to float and both ints and floats can be cast to complex numbers.
->  Complex numbers can be converted to ints and floats.
-> Any object can be cast to a String
-> Strings can be to numerical types if the string represents a valid number.

CASTING IS DONE USING FUNCTIONS bool, int, float, complex and str.


"""

bool(42)  #Convert integer to boolean

bool(1)   #Any nonzero value counts as True

bool(0)   #Zero equates to False

bool("")   #An empty string is also False

int(2.99)   #Convert float to integer (the decimal part is decarded)

int("22")   #Convert string to int

float("4.567")   #Convert string to float

complex("1+2j")   #Convert string to complex

float(10)  #Convert integer to float

complex(10)  #Convert integer to complex number

str(True)  #Convert boolean to string

str(1)  #Convert integer 1  to string"1"

str(1.234)  #Convert float to string