# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN_0UBbJtj-M365g6AoV2-cKJbh8GsEI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics as st
data=pd.read_csv('/content/StudentPerformanceFactors.csv')
print(data.head())
sales_data = data['Exam_Score'].dropna()
print(sales_data)
mean_value = np.mean(sales_data)
print("Mean:", mean_value)
median_value = np.median(sales_data)
print("Median:", median_value)
mode_value = st.mode(sales_data)
print("Mode:", mode_value)

mean=np.mean(sales_data)
print("Mean:", mean)
sd=np.std(sales_data)
print("Standard Deviation:", sd)

import statistics as st
import matplotlib.pyplot as plt
data=pd.read_csv('/content/StudentPerformanceFactors.csv')
print(data.head())
sales_data = data['Exam_Score'].dropna()
skewness=st.skew(sales_data)
print("Skewness:", skewness)
if(skewness>0):
  print("The distribution has positive")
elif(skewness<0):
  print("The distribution has Negative")
else:
  print("The distribution is symmetric")
  kurtosis=st.kurtosis(sales_data)
  print("Kurtosis:", kurtosis)
  if(kurtosis>0):
    print("The distribution has positive")
  elif(kurtosis<0):
    print("The distribution has Negative")
  else:
    print("The distribution is symmetric")

import matplotlib.pyplot as plt
 data=pd.read_csv('/content/StudentPerformanceFactors.csv')
 print(data.head())
 sales_data = data['Exam_Score'].dropna()
 plt.hist(sales_data,bins=10)
 plt.xlabel('Exam_Score')
 plt.ylabel('Frequency')
 plt.title('Histogram of Exam_Score')
 plt.show()